# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "OOPCardsSimpleViews" do

end

target "OOPCardsSimpleViewsTests" do
  pod 'Specta',      '~> 0.2.1'                                                 

  pod 'Expecta',     '~> 0.2.4'                                                 

  pod 'KIF', '~> 3.0'                                                           

  pod 'Swizzlean', '~> 0.1.1'  
end

